### ISSUE TITLE
Not able to generate .json file 

### ISSUE THREAD

**Issue by Harshdeep4295** [IBM/get-started-openapi#1]
I am using, 
swagger-inline './server.js' --base './openapi/openapiBase.yaml' --format '.json' --out './openapi/openapi.json'
in terminal to create the .json file but i am not able to generate the file as described also i am getting the below message 

1 files matched...
0 swagger definitions found...
swagger.json created!

**Comment by hickeyma** [comment]
Did you add the OpenAPI endpoints inline comments to the application API endpoints? Refer to point 2 [here](https://github.com/IBM/get-started-openapi/blob/master/docs/draftOpenAPIChallenge.md#steps)

**Comment by Harshdeep4295** [comment]
Hi @hickeyma I did add comments, here is what I get when i tried to generate the swagger file

dev@xavi:i$ swagger-inline './server.js' --base './openapi/openapiBase.yaml' --format '.json' --out './openapi/openapi.json'
1 files matched...
0 swagger definitions found...
swagger.json created!

Please tell me where did I go wrong!

here is my server.js file attached
[server.txt](https://github.com/IBM/get-started-openapi/files/2762969/server.txt)

**Comment by popalex** [comment]
Hello,

I am having the same problem.
The server.js file is the same as @Harshdeep4295 .

**Comment by hickeyma** [comment]
@Harshdeep4295 I checked the attached server.js file and it is the same as the version of the file in the [repo](https://github.com/IBM/get-started-openapi/blob/master/server.js). Did you attach the original by accident and not your version with the OpenAPI endpoints inline comments?

**Comment by Harshdeep4295** [comment]
Ohh i guess i forgot to ads the openapi endpoints inline comments.. Though
how to add those if you could help me out ob this?

**Comment by hickeyma** [comment]
That's the learning part. :) Use the [swagger-inline example](https://www.npmjs.com/package/swagger-inline#1-create-a-project) and the [OAS 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) as your guide. Lots of info online also.

Here is a strater sample:
```console
/*
 * @api [get] /visitors
 * description: "Returns all visitors"
 * responses:
 *   "200":
 *     description: "A list of visitors."
 *     schema:
 *       type: "array"
 *       items:
 *         $ref: "#/definitions/visitor"
 */
```

Once you add the comments to each endpoint, then the `swagger-inline` command can generate the OAS.

**Comment by timroster** [comment]
It would be helpful to provide a suggestion in the OpenAPI Experience that the swagger inline base (aka: `openapiBase.yaml` ) file _could_ be edited to add in the definition for the `visitor` object. Right now, that challenge only suggests annotating the `server.js` file with the comments for the APIs

**Comment by hickeyma** [comment]
Good idea @timroster. This is covered in #3
